export const DEFAULT_CLIENT_COLUMNS = [
  {headerName: 'LastName', field: 'LastName'},
  {headerName: 'FirstName', field: 'FirstName'},
  {headerName: 'Status', field: 'Status'},
  {headerName: 'Phone', field: 'Phone'},
  {headerName: 'City', field: 'City'},
  {headerName: 'Zip', field: 'Zip'},
  {headerName: 'ClientTypeName', field: 'ClientTypeName'}
];

export const CLIENT_COLUMNS = [
  {headerName: 'ClientId', field: 'ClientId'},
  {headerName: 'FirstName', field: 'FirstName'},
  {headerName: 'MiddleInitial', field: 'MiddleInit'},
  {headerName: 'LastName', field: 'LastName'},
  {headerName: 'DateOfBirth', field: 'DateOfBirth'},
  {headerName: 'Address1', field: 'Address1'},
  {headerName: 'City', field: 'City'},
  {headerName: 'County', field: 'County'},
  {headerName: 'Zip', field: 'Zip'},
  {headerName: 'Status', field: 'Status'},
  {headerName: 'Gender', field: 'str_Gender'},
  {headerName: 'Phone', field: 'Phone'},
  {headerName: 'Weight', field: 'Weight'},
  {headerName: 'ServiceStartDate', field: 'ServiceStartDate'},
  {headerName: 'ServiceEndDate', field: 'ServiceEndDate'},
  {headerName: 'Reason', field: 'str_reason'},
  {headerName: 'Email', field: 'Email'},
  {headerName: 'ClientTypeName', field: 'ClientTypeName'},
  {headerName: 'Ambulatory', field: 'Ambulatory'},
  {headerName: 'ReferredByName', field: 'ReferredByName'},
  {headerName: 'RefNumber', field: 'RefNumber'},
  {headerName: 'DNR', field: 'DNR'},
  {headerName: 'Physician', field: 'Physician'},
  {headerName: 'PrimaryDiagnosis', field: 'PrimaryDiagnosis'},
  {headerName: 'Priority', field: 'Priority'},
  {headerName: 'QuickbooksId', field: 'QuickbooksId'},
  {headerName: 'InitialContactID', field: 'InitialContactID'},
  {headerName: 'MedicalRecord#', field: 'MedicalRecord#'},
  {headerName: 'LocationID', field: 'locationID'},
  {headerName: 'Notes', field: 'Notes'},
  {headerName: 'AccountingID', field: 'AccountingID'},
  {headerName: 'CaseManagerName', field: 'CaseManagerName'},
  {headerName: 'TelephonyID', field: 'telephonyID'},
  {headerName: 'FirstVisitDate', field: 'FirstVisitDate'},
  {headerName: 'LastVisitDate', field: 'LastVisitDate'}
];

export const DEFAULT_CAREGIVER_COLUMNS = [
  {headerName: 'FirstName', field: 'FirstName'},
  {headerName: 'LastName', field: 'LastName'},
  {headerName: 'Status', field: 'Status'},
  {headerName: 'Phone1', field: 'Phone1'},
  {headerName: 'City', field: 'City'},
  {headerName: 'Zip', field: 'Zip'},
  {headerName: 'HireDate', field: 'StatusDate'},
  {headerName: 'Class', field: 'Class'},
  {headerName: 'NPI', field: 'NPI'},
  {headerName: 'Country', field: 'className'}
];

export const CAREGIVER_COLUMNS = [
  {headerName: 'FirstName', field: 'FirstName'},
  {headerName: 'MiddleInitial', field: 'MiddleInit'},
  {headerName: 'LastName', field: 'LastName'},
  {headerName: 'Address1', field: 'Address1'},
  {headerName: 'City', field: 'City'},
  {headerName: 'Zip', field: 'Zip'},
  {headerName: 'Gender', field: 'str_Gender'},
  {headerName: 'Class', field: 'Class'},
  {headerName: 'Status', field: 'Status'},
  {headerName: 'Reason', field: 'str_reason'},
  {headerName: 'Phone1', field: 'Phone1'},
  {headerName: 'SocialSecurityNum', field: 'SocialSecurityNum'},
  {headerName: 'HireDate', field: 'StatusDate'},
  {headerName: 'TermDate', field: 'InactiveDate'},
  {headerName: 'DateofBirth', field: 'DateofBirth'},
  {headerName: 'Email', field: 'Email'},
  {headerName: 'NPI', field: 'NPI'},
  {headerName: 'DoNotRehire', field: 'doNotRehire'},
  {headerName: 'IndependentContractor', field: 'independentContractor'},
  {headerName: 'ValidDriversLicense', field: 'ValidDriversLicense'},
  {headerName: 'Smoker', field: 'Smoker'},
  {headerName: 'WeightRestriction', field: 'WeightRestriction'},
  {headerName: 'BackgroundCheck', field: 'BackgroundCheck'},
  {headerName: 'Country', field: 'className'},
  {headerName: 'TextMessage', field: 'TextMessage'},
  {headerName: 'Availabilities', field: 'Availabilities'},
  {headerName: 'FirstVisitDate', field: 'FirstVisitDate'},
  {headerName: 'LastVisitDate', field: 'LastVisitDate'}
];
